services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        # Uncomment to enable authentication
        calls:
            - ['authenticate', ['%env(GITHUB_API_TOKEN)%', null, !php/const Github\AuthMethod::ACCESS_TOKEN]]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'
