services:
    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'

    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        calls:
            - [ 'authenticate', [ '%env(GITHUB_API_TOKEN)%', null, !php/const Github\AuthMethod::ACCESS_TOKEN ] ]
            - [ 'addCache', [ '@cache.github' ] ]
