# Check documentation at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_ENV: 'test'
  APP_DEBUG: '0'
  PHP_CS_FIXER_IGNORE_ENV: '1'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2, flex, php-cs-fixer, phpmd
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Restore composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-
        continue-on-error: true
      - name: Install project dependencies
        run: composer install --prefer-dist --no-scripts --no-progress
      - name: Run PHP-CS-Fixer analysis
        run: php-cs-fixer fix --ansi --dry-run --diff
      - name: Run PHP Mess Detector analysis
        run: phpmd src text phpmd.xml
      - name: Run Linter analysis
        run: |
          bin/console lint:yaml config --parse-tags
          bin/console lint:container
      - name: Run Rector analysis
        run: vendor/bin/rector process --dry-run
