# Check documentation at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

env:
  APP_ENV: 'test'
  APP_DEBUG: '0'

jobs:
  tests:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, flex, php-cs-fixer, phpstan, phpmd
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Restore composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-
        continue-on-error: true
      - name: Install project dependencies
        run: composer install --prefer-dist --no-scripts --no-progress
      - name: Run PHP-CS-Fixer analysis
        run: php-cs-fixer fix --ansi --dry-run --diff
      - name: Cache PHPStan
        uses: actions/cache@v2
        with:
          path: .phpstan/
          key: phpstan-${{ github.sha }}
          restore-keys: phpstan-
      - name: Run PHPStan analysis
        run: phpstan analyze
      - name: Run PHP Mess Detector analysis
        run: phpmd src text phpmd.xml
      - name: Run Linter analysis
        run: bin/console lint:yaml config --parse-tags
      - name: Run Rector analysis
        run: vendor/bin/rector process
